<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="HrEmployeeSDOService"
     targetNamespace="/model/common/"
     xmlns:ns1="/model/common/"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <plnk:partnerLinkType name="HrEmployeeSDOService_PL">
        <plnk:role name="HrEmployeeSDOService_Role">
            <plnk:portType name="ns1:HrEmployeeSDOService"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:import namespace="/model/common/" location="http://stuart-pc:7001/HrEmployeeSDO/HrEmployeeSDOService?WSDL"/>
</wsdl:definitions>
