package model;

import oracle.jbo.RowSetIterator;
import oracle.jbo.ViewObject;
import oracle.jbo.server.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Dec 13 22:14:30 EST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HrEmployeeSDOImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public HrEmployeeSDOImpl() {
    }
    
    public oracle.sql.NUMBER  VOCycleByRowSetBest(){
        ViewObject vo = getEmployeesView1();
        oracle.sql.NUMBER topTenSal = new oracle.sql.NUMBER(0) ;
        // create secondary row set iterator with system-assigned name
        // Best way to cycle through VO data.  
        // We get the attributes and then pull in
        RowSetIterator items = vo.createRowSetIterator(null);
        vo.setSortBy("Salary asc");
        int i = 0 ;
        while (items.hasNext()) {
            EmployeesViewRowImpl r = (EmployeesViewRowImpl) items.next();
            if (i < 11){
                topTenSal = r.getSalary() ;
                System.out.println("sal " + topTenSal) ;
            } else {
 
            }
            i++;
        }    
        System.out.println("The top salary is " + topTenSal) ;
        return topTenSal ;
    }


    /**
     * Container's getter for EmployeesView1.
     * @return EmployeesView1
     */
    public EmployeesViewImpl getEmployeesView1() {
        return (EmployeesViewImpl)findViewObject("EmployeesView1");
    }
}
